# اسم الـ Workflow الخاص بتطبيق فتاوى العراق
workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - ios_signing # تأكد أنك أنشأت هذه المجموعة في الإعدادات وضعت فيها الـ API Keys
      vars:
        BUNDLE_ID: "com.iraqfatawa.app" # تأكد من مطابقة هذا المعرف لتطبيقك
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up code signing settings on Codemagic
        script: | 
          keychain initialize
      - name: Fetch signing files from App Store Connect
        script: | 
          # هذا الأمر يحل مشكلة Private Key المفقود بإنشاء شهادة جديدة (--create)
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Set up code signing identities
        script: | 
          keychain add-certificates
      - name: Flutter build ipa
        script: | 
          flutter build ipa --release \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - bake16t@gmail.com # ضع إيميلك هنا لتصلك النتيجة