# فتاوى العراق — Codemagic: بناء Android و iOS
# ارفع المشروع على GitHub ثم أضف التطبيق في codemagic.io وربط الريبو.
# أضف في Codemagic: Android keystore (مرجع fatwa_keystore) + iOS شهادات وملف توزيع.

workflows:
  android-release:
    name: Android Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - fatwa_keystore   # اسم مرجع الـ keystore بعد رفعه في Codemagic → Code signing identities → Android keystores
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
        PACKAGE_NAME: "com.iraqifatawa.app"
    scripts:
      - name: Install .NET 9 SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH --channel 9.0
      - name: Install MAUI workload (Android)
        script: |
          $DOTNET nuget locals all --clear
          $DOTNET workload install android maui --source https://api.nuget.org/v3/index.json
      - name: Build Android (AAB للـ Play Store)
        script: |
          export ANDROID_KEYSTORE_PATH="$CM_KEYSTORE_PATH"
          export ANDROID_KEYSTORE_PASSWORD="$CM_KEYSTORE_PASSWORD"
          export ANDROID_KEY_ALIAS="$CM_KEY_ALIAS"
          export ANDROID_KEY_PASSWORD="$CM_KEY_PASSWORD"
          $DOTNET publish -f net9.0-android -c Release \
            -p:AndroidPackageFormat=aab \
            -p:AndroidKeyStore=True \
            -p:AndroidSigningKeyStore="$CM_KEYSTORE_PATH" \
            -p:AndroidSigningStorePass="$CM_KEYSTORE_PASSWORD" \
            -p:AndroidSigningKeyAlias="$CM_KEY_ALIAS" \
            -p:AndroidSigningKeyPass="$CM_KEY_PASSWORD" \
            -o ./artifacts/android
    artifacts:
      - ./artifacts/android/*.aab
      - ./artifacts/android/*.apk
    publishing:
      email:
        recipients:
          - fatwairaq@gmail.com
        notify:
          success: true
          failure: true

  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.iraqifatawa.app
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
        BUNDLE_ID: "com.iraqifatawa.app"
    scripts:
      - name: Install .NET 9 SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH --channel 9.0
      - name: Install MAUI workload (iOS)
        script: |
          $DOTNET nuget locals all --clear
          $DOTNET workload install ios maui --source https://api.nuget.org/v3/index.json
      - name: Set Info.plist (export compliance)
        script: |
          PLIST="$CM_BUILD_DIR/Platforms/iOS/Info.plist"
          if [ -f "$PLIST" ]; then
            /usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" "$PLIST" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Set :ITSAppUsesNonExemptEncryption false" "$PLIST" 2>/dev/null || true
          fi
      - name: Build iOS (IPA)
        script: |
          CERT_NAME=$(keychain list-certificates | jq -r '.[] | .common_name' | head -1)
          for f in ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision; do
            [ -f "$f" ] || continue
            PROFILE_NAME=$(security cms -D -i "$f" 2>/dev/null | /usr/libexec/PlistBuddy -c "print :Name" /dev/stdin 2>/dev/null)
            [ -n "$PROFILE_NAME" ] && break
          done
          $DOTNET publish -f net9.0-ios -c Release \
            -p:BuildIpa=True \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:CodesignKey="$CERT_NAME" \
            -p:CodesignProvision="$PROFILE_NAME" \
            -o ./artifacts/ios
    artifacts:
      - ./artifacts/ios/*.ipa
    publishing:
      email:
        recipients:
          - fatwairaq@gmail.com
        notify:
          success: true
          failure: true
