ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    # استخدم اسم المفتاح أو الاسم الظاهر في الإعدادات
    integrations:
      app_store_connect: "Seyfeddin Ozturk" 
    environment:
      groups:
        - apple_auth
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
        BUNDLE_ID: "com.iraqifatawa.app"
    scripts:
      - name: Install .NET 9 SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH --channel 9.0
      - name: Install MAUI workload (iOS)
        script: |
          $DOTNET nuget locals all --clear
          $DOTNET workload install ios maui --source https://api.nuget.org/v3/index.json
      - name: Set up keychain for code signing
        script: |
          keychain initialize
      - name: Fetch signing files from App Store Connect
        script: |
          # هنا سيستخدم المفتاح المربوط لجلب الملفات
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set Info.plist (export compliance)
        script: |
          PLIST="$CM_BUILD_DIR/Platforms/iOS/Info.plist"
          if [ -f "$PLIST" ]; then
            /usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" "$PLIST" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Set :ITSAppUsesNonExemptEncryption false" "$PLIST" 2>/dev/null || true
          fi
      - name: Build iOS (IPA)
        script: |
          CERT_NAME=$(keychain list-certificates | jq -r '.[] | .common_name' | head -1)
          PROFILE_NAME=""
          for f in ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision; do
            [ -f "$f" ] || continue
            PROFILE_NAME=$(security cms -D -i "$f" 2>/dev/null | /usr/libexec/PlistBuddy -c "print :Name" /dev/stdin 2>/dev/null)
            [ -n "$PROFILE_NAME" ] && break
          done
          $DOTNET publish -f net9.0-ios -c Release \
            -p:BuildIpa=True \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:CodesignKey="$CERT_NAME" \
            -p:CodesignProvision="$PROFILE_NAME" \
            -o ./artifacts/ios
    artifacts:
      - ./artifacts/ios/*.ipa
    publishing:
      app_store_connect:
        auth: integration
      email:
        recipients:
          - fatwairaq@gmail.com
        notify:
          success: true
          failure: true